name: simple_cubit_app
description: A simple Flutter application implementing the Cubit pattern for state management with two screens: a login screen and a home screen with a logout button.
version: 1.0.0
environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  bloc: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^8.0.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true